/* |UXUIDC| SEO helpers
 * Centralized metadata builder so every page ships:
 * - absolute canonical
 * - full OpenGraph (siteName, type, locale, images)
 * - Twitter card (summary_large_image)
 * - explicit robots index/follow
 * Title length target: 50 to 60 chars.
 * Description length target: 150 to 160 chars.
 */

import type { Metadata } from "next";

export const SITE_URL = "https://www.cogai.health";
export const SITE_NAME = "COGAI";
export const TWITTER_HANDLE = "@cogai";

// Generated by app/opengraph-image.tsx. Resolved against metadataBase
// (set in app/layout.tsx) into an absolute URL by Next.js.
const DEFAULT_OG_IMAGE = "/opengraph-image";

interface BuildMetadataInput {
  title: string;
  description: string;
  path: string;
  ogTitle?: string;
  ogDescription?: string;
  twitterTitle?: string;
  twitterDescription?: string;
  image?: string;
  imageAlt?: string;
  noindex?: boolean;
  keywords?: string[];
}

export function buildMetadata(input: BuildMetadataInput): Metadata {
  const {
    title,
    description,
    path,
    ogTitle,
    ogDescription,
    twitterTitle,
    twitterDescription,
    image = DEFAULT_OG_IMAGE,
    imageAlt = `${SITE_NAME}. Cognitive health, measured.`,
    noindex = false,
    keywords,
  } = input;

  const url = path.startsWith("http") ? path : `${SITE_URL}${path}`;

  return {
    // Use absolute so callers control the full title; the layout's
    // title.template ("%s | COGAI") would otherwise append "COGAI"
    // again to titles that already include the brand.
    title: { absolute: title },
    description,
    keywords,
    alternates: { canonical: url },
    robots: noindex
      ? { index: false, follow: false }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-video-preview": -1,
            "max-image-preview": "large",
            "max-snippet": -1,
          },
        },
    openGraph: {
      title: ogTitle ?? title,
      description: ogDescription ?? description,
      url,
      siteName: SITE_NAME,
      type: "website",
      locale: "en_US",
      images: [
        {
          url: image,
          width: 1200,
          height: 630,
          alt: imageAlt,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: twitterTitle ?? ogTitle ?? title,
      description: twitterDescription ?? ogDescription ?? description,
      images: [image],
      site: TWITTER_HANDLE,
      creator: TWITTER_HANDLE,
    },
  };
}
